language: objective-c

before_install:
  - sudo gem install cocoapods
  
script: "xcodebuild test -workspace RandomHighwaySign.xcworkspace -scheme \"RandomHighwaySign iOS\" -destination \"platform=iOS Simulator,name=iPhone 5\""
