language: objective-c
osx_image: xcode8

before_install:
  - gem install cocoapods -v '1.1.0.rc.2'
  - brew update 
  - brew reinstall xctool
  - bundle install
  - rake api_plist
  - bundle exec pod repo update

cache:
  - cocoapods
  - bundler

script:
  - xcodebuild clean build -workspace RandomHighwaySign.xcworkspace -scheme RandomHighwaySign CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
#xcode_workspace: RandomHighwaySign.xcworkspace
#script: xctool -workspace RandomHighwaySign.xcworkspace -scheme RandomHighwaySign CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
#xcode_scheme: RandomHighwaySign
xcode_sdk: iphoneos10.0
