language: objective-c
osx_image: beta-xcode6.3

before_install:
  - brew update 
  - brew reinstall xctool
  - bundle install

cache:
  - cocoapods
  - bundler

xcode_workspace: RandomHighwaySign.xcworkspace
xcode_scheme: RandomHighwaySign
xcode_sdk: iphonesimulator8.3
