language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods -v '0.32.1'
  - brew update 
  - brew reinstall xctool
  - bundle install
  - rake api_plist

cache:
  - cocoapods
  - bundler

#xcode_workspace: RandomHighwaySign.xcworkspace
script: xctool -workspace RandomHighwaySign.xsworkspace -scheme RandomHighwaySign CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
#xcode_scheme: RandomHighwaySign
xcode_sdk: iphoneos9.2
