language: objective-c

before_install:
  - brew update 
  - brew reinstall xctool
  - bundle install

cache:
  - cocoapods
  - bundler

xcode_project: RandomHighwaySign.xcodeproj
xcode_scheme: RandomHighwaySign
